<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="kevoree">
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="/0/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1" eType="/0/Port" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1" eType="/0/Port" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="/0/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaData" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="started" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinition" eType="/0/TypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dictionary" eType="/0/Dictionary" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentDictionary" upperBound="-1" eType="/0/FragmentDictionary" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1" eType="/0/MBinding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="portTypeRef" eType="/0/PortTypeRef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" eType="/0/Instance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="/0/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1" eType="/0/PortTypeRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1" eType="/0/PortTypeRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="/2" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryBean" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bean" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployUnit" eType="/0/DeployUnit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dictionaryType" eType="/0/DictionaryType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1" eType="/0/TypeDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortTypeRef" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="noDependency" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="/0/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1" eType="/0/PortTypeMapping" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContainerNode" eSuperTypes="/0/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1" eType="/0/ComponentInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hosts" upperBound="-1" eType="/0/ContainerNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="host" eType="/0/ContainerNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1" eType="/0/Group"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="networkInformation" upperBound="-1" eType="/0/NetworkInfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="/0/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subNodes" upperBound="-1" eType="/0/ContainerNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkInfo" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1" eType="/0/NetworkProperty" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContainerRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="/0/ContainerNode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinitions" upperBound="-1" eType="/0/TypeDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1" eType="/0/Repository" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1" eType="/0/TypedElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1" eType="/0/TypeLibrary" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hubs" upperBound="-1" eType="/0/Channel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mBindings" upperBound="-1" eType="/0/MBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployUnits" upperBound="-1" eType="/0/DeployUnit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeNetworks" upperBound="-1" eType="/0/NodeNetwork" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1" eType="/0/Group" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Repository">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="/2" iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="genericTypes" upperBound="-1" eType="/0/TypedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeLibrary" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1" eType="/0/TypeDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Channel" eSuperTypes="/0/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1" eType="/0/MBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="/0/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hub" eType="/0/Channel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeployUnit" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="/2" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="/2" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hashcode" eType="/2" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredLibs" upperBound="-1" eType="/0/DeployUnit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeNetwork">
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="/0/NodeLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initBy" eType="/0/ContainerNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="/0/ContainerNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortType" eSuperTypes="/0/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchrone" eType="/1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/2" iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dictionary">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1" eType="/0/DictionaryValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/2" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="/2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FragmentDictionary" eSuperTypes="/0/Dictionary">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/2" iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1" eType="/0/DictionaryAttribute" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryAttribute" eSuperTypes="/0/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragmentDependant" eType="/1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="/2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortTypeMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="beanMethodName" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceMethodName" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramTypes" eType="/2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServicePortType" eSuperTypes="/0/PortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1" eType="/0/Operation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="/0/TypedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="/3"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="/0/TypedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessagePortType" eSuperTypes="/0/PortType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1" eType="/0/TypedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeLink">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkType" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="estimatedRate" eType="/3"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastCheck" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoneID" eType="/2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="networkProperties" upperBound="-1" eType="/0/NetworkProperty" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkProperty" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/2" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="/2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChannelType" eSuperTypes="/0/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBindings" eType="/3"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBindings" eType="/3"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerFragments" eType="/3"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperFragments" eType="/3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GroupType" eSuperTypes="/0/TypeDefinition"/>
    <eClassifiers xsi:type="ecore:EClass" name="NodeType" eSuperTypes="/0/TypeDefinition"/>
  </ecore:EPackage>
  <ecore:EDataType name="java.lang.Boolean"/>
  <ecore:EDataType name="java.lang.String"/>
  <ecore:EDataType name="java.lang.Integer"/>
</xmi:XMI>
