<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kmf"
    nsURI="http://kmf" nsPrefix="kmf">
  <eSubpackages name="test" nsURI="http://kmf.test" nsPrefix="kmf.test">
    <eClassifiers xsi:type="ecore:EClass" name="Container">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bees" upperBound="-1"
          eType="#//test/B" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
          eType="#//test/DataTypesTest" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="A">
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_optionalSingleB"
          eType="#//test/B" eOpposite="#//test/B/optionalSingleA_optionalSingleB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_MandatorySingleB"
          eType="#//test/B" eOpposite="#//test/B/optionalSingleA_MandatorySingleB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_StarListB"
          eType="#//test/B" eOpposite="#//test/B/optionalSingleA_StarListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleA_mandatorySingleB"
          lowerBound="1" eType="#//test/B" eOpposite="#//test/B/mandatorySingleA_mandatorySingleB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_PlusListB"
          eType="#//test/B" eOpposite="#//test/B/optionalSingleA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleA_StartListB"
          lowerBound="1" eType="#//test/B" eOpposite="#//test/B/mandatorySingleA_StarListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleA_PlusListB"
          lowerBound="1" eType="#//test/B" eOpposite="#//test/B/mandatorySingleA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="StarListA_StarListB"
          upperBound="-1" eType="#//test/B" eOpposite="#//test/B/StarListA_StarListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="StarListA_PlusListB"
          upperBound="-1" eType="#//test/B" eOpposite="#//test/B/StarListA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PlusListA_PlusListB"
          lowerBound="1" upperBound="-1" eType="#//test/B" eOpposite="#//test/B/PlusListA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleRef" eType="#//test/B"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleRef" lowerBound="1"
          eType="#//test/B"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="starList" upperBound="-1"
          eType="#//test/B"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="plusList" lowerBound="1"
          upperBound="-1" eType="#//test/B"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B">
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_optionalSingleB"
          eType="#//test/A" containment="true" eOpposite="#//test/A/optionalSingleA_optionalSingleB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_MandatorySingleB"
          lowerBound="1" eType="#//test/A" containment="true" eOpposite="#//test/A/optionalSingleA_MandatorySingleB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_StarListB"
          upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/optionalSingleA_StarListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleA_mandatorySingleB"
          lowerBound="1" eType="#//test/A" containment="true" eOpposite="#//test/A/mandatorySingleA_mandatorySingleB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleA_PlusListB"
          lowerBound="1" upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/optionalSingleA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleA_StarListB"
          upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/mandatorySingleA_StartListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleA_PlusListB"
          lowerBound="1" upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/mandatorySingleA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="StarListA_StarListB"
          upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/StarListA_StarListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="StarListA_PlusListB"
          lowerBound="1" upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/StarListA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PlusListA_PlusListB"
          lowerBound="1" upperBound="-1" eType="#//test/A" containment="true" eOpposite="#//test/A/PlusListA_PlusListB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionalSingleRef" eType="#//test/A"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mandatorySingleRef" lowerBound="1"
          eType="#//test/A" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="starList" upperBound="-1"
          eType="#//test/A" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="plusList" lowerBound="1"
          upperBound="-1" eType="#//test/A" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataTypesTest">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigDecimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="char" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="charObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ECharacterObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="double" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="list" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="float" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="long" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="map" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="short" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="treeIterator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ETreeIterator"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
