<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudml" nsURI="http://cloudml.org" nsPrefix="org.cloudml">
  <eSubpackages name="core" nsURI="http://org.cloudml/core" nsPrefix="org.cloudml.core">
    <eClassifiers xsi:type="ecore:EClass" name="CloudMLElement" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//core/CloudMLElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WithProperties" abstract="true" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//core/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="retrievingResourceCommand"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployingResourceCommand"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentModel" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactTypes" upperBound="-1"
          eType="#//core/Artefact" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeTypes" upperBound="-1"
          eType="#//core/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactInstances" upperBound="-1"
          eType="#//core/ArtefactInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeInstances" upperBound="-1"
          eType="#//core/NodeInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPort" eSuperTypes="#//core/WithProperties"/>
    <eClassifiers xsi:type="ecore:EClass" name="Artefact" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//core/ArtefactPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//core/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
          eType="#//core/ArtefactPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
          eType="#//core/ArtefactPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
          eType="#//core/ArtefactPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/ArtefactPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodePort" eSuperTypes="#//core/WithProperties"/>
    <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/NodePort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudProvider" lowerBound="1"
          eType="#//core/Provider"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minDisk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="privateKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is64os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPortInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/ArtefactPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Artefact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//core/NodePortInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
          eType="#//core/ArtefactPortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
          eType="#//core/ArtefactPortInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
          eType="#//core/ArtefactPortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/ArtefactPortInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodePortInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/NodePort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/NodeInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/NodePortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedArtefacts" upperBound="-1"
          eType="#//core/ArtefactInstance" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
