<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evaluation" nsURI="http://evaluation/1.0" nsPrefix="evaluation">
  <eClassifiers xsi:type="ecore:EClass" name="SmartGrid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="smartmeters" upperBound="-1"
        eType="#//SmartMeter" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="customers" upperBound="-1"
                eType="#//Customer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartMeter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbors" upperBound="-1"
        eType="#//SmartMeter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="electricLoad" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbors" upperBound="-1"
        eType="#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="meters" upperBound="-1"
                        eType="#//SmartMeter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
