site_name: Kevoree Modeling Framework
pages:
- [index.md, Home]
- [start.md, Getting Started in Java]
- [start_js.md, Getting Started in JavaScript]
- [promise.md, Promise API]
- [reflexive.md, Reflexive API]
- [about.md, About]
theme: readthedocs